name: Reproduce bug when urllib3 v2 outputs warning about LibreSSL 2.8.3
on:
  push:
  workflow_dispatch:
jobs:
  repro:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-intel
          - macos-26-intel
          - macos-14
          - macos-15
          - macos-26
          - xcode-27
    steps:
      - name: Create venv with Apple system Python
        shell: bash
        run: |
          path="$RUNNER_TEMP/system-python-venv"
          /usr/bin/python3 -m venv "$path"
          echo "$path/bin" | tee -a "$GITHUB_PATH"

      - name: Print Python details
        shell: python
        run: |
          import sys
          import ssl
          
          print(sys.executable)
          print(sys.version)
          print(ssl.OPENSSL_VERSION)

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: jurplel/install-qt-action
          ref: 65312ef606a0962fb2372197b37393792e88c2ce

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0 
        with: 
          node-version: 24 
          cache: npm 
          cache-dependency-path: action/ 
  
      - run: | 
          cd action 
          npm ci || npm install 
          npm run build 
        shell: bash
  
      # See the root "action.yml" file. 
      - name: Use local built internal action (hack)
        run: |
          sed -i.bak 's|uses: $/action|uses: ./action|' action.yml 
          diff -u action.yml.bak action.yml || true 
          git status --porcelain 
        shell: bash
  
      - name: Install Qt
        uses: ./
        with:
          # Do NOT let "actions/setup-python" download Python with OpenSSL backend.
          setup-python: false
          # For Python 3.9.6 on macOS; https://pypi.org/project/py7zr/1.0.0/ .
          py7zrversion: ==1.0.0
          # "aqt list-qt ..." will still be called.
          extra: --dry-run
